<?php

function extlink_menu() {
  $items = array();
  $items['admin/config/user-interface/extlink'] = array(
    'title' => 'External links',
    'description' => 'Alter the display of external links on the site.',
    'route_name' => 'extlink_admin_settings',
  );
  return $items;
}

/**
 * Implementation of hook_library_info().
 */
function extlink_library_info(){
  $path = drupal_get_path('module', 'extlink');
  $libraries['extlink'] = array(
    'title' => 'extlink javascript and css.',
    'version' => '1.0',
    'js' => array($path . '/extlink.min.js' => array(),
    ),
    'css' => array($path . '/extlink.css' => array(),
    ),
    'dependencies' => array(
      array('system', 'jquery'),
      array('system', 'drupal'),
      array('system', 'drupalSettings'),
      array('system', 'jquery.once'),
    ),
  );
  return $libraries;
}

/**
 * Implementation of hook_page_build() ().
 */
function extlink_page_build(&$page) {
  $config = config('extlink.settings');
  $page['#attached']['library'][] = array('extlink', 'extlink');
  
  drupal_add_js(array('extlink' => array(
    'extTarget'     => $config->get('extlink_target'),
    'extClass'      => $config->get('extlink_class'),
    'extSubdomains' => $config->get('extlink_subdomains'),
    'extExclude'    => $config->get('extlink_exclude'),
    'extInclude'    => $config->get('extlink_include'),
    'extAlert'      => $config->get('extlink_alert'),
    'extAlertText'  => $config->get('extlink_alert_text'),
    'mailtoClass'   => $config->get('extlink_mailto_class'))), 'setting'
  );
}
