<?php

function extlink_menu() {
  $items = array();
  $items['admin/config/user-interface/extlink'] = array(
    'title' => 'External links',
    'description' => 'Alter the display of external links on the site.',
    'route_name' => 'extlink_admin_settings',
  );
  return $items;
}

/**
 * Implementation of hook_library_info().
 */
function extlink_library_info(){
  $libraries['extlink.jscript'] = array(
    'title' => 'extlink javascript behavior/logic.',
    'js' => array(
      drupal_get_path('module', 'extlink') . '/extlink.js' => array(),
    ),
    'dependencies' => array(
      array('system', 'jquery'),
      array('system', 'drupal'),
      array('system', 'drupalSettings'),
      array('system', 'jquery.once'),
    ),
  );
  return $libraries;
}

/**
 * Implementation of hook_init().
 */
function extlink_init() {
  $path = drupal_get_path('module', 'extlink');
  drupal_add_js($path .'/extlink.js', array('every_page' => TRUE));
  drupal_add_js(array('extlink' => array(
    'extTarget'     => variable_get('extlink_target', 0),
    'extClass'      => variable_get('extlink_class', 'ext'),
    'extSubdomains' => variable_get('extlink_subdomains', 1),
    'extExclude'    => variable_get('extlink_exclude', ''),
    'extInclude'    => variable_get('extlink_include', ''),
    'extAlert'      => variable_get('extlink_alert', 0),
    'extAlertText'  => variable_get('extlink_alert_text', 'This link will take you to an external web site. We are not responsible for their content.'),
    'mailtoClass'   => variable_get('extlink_mailto_class', 'mailto'))), 'setting'
  );
  if (variable_get('extlink_class', 'ext') == 'ext' || variable_get('extlink_mailto_class', 'mailto') == 'mailto') {
    drupal_add_css($path . '/extlink.css', array('every_page' => TRUE));
  }
}
